plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - README.md
title: OBSIDIAN Level Maker
description: A community continuation of the OBLIGE Level Maker
theme: jekyll-theme-slate