plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - README.md
title: OBSIDIAN Level Maker
description: Welcome to the Infinite Hells
theme: jekyll-theme-midnight